/*use Gallery;
drop table Pools_Pictures;
drop table Tags_Pictures;
drop table ChildPools;
drop table Reposts;
drop table Watches;
drop table Pictures;
drop table Artists;
drop table Pools;
drop table Sites;
drop table Tags;
drop table Users;
drop function get_pictures_by_tag;
drop function get_user_artists;
drop function get_artist_pools;
drop function pictures_uploaded_in;
drop function get_count_uploads_artists;
drop function most_popular_by_uploads_artist;
drop function pictures_watched_in;
drop function get_count_watches_artists;
drop function most_popular_by_watches_artist;
drop function get_pictures_watched_by_user;
drop function get_pictures_reposted_by_user;
drop function get_pictures_watched_not_reposted;
drop function get_pictures_reposted_not_watched;
drop type T_PicturesID;
drop type T_UsersID;
drop type T_PoolsID;
drop type T_TagsID;
drop type T_ArtistsID;
drop type T_SitesID;
drop type T_WatchesID;
drop type T_Pools_PicturesID;
drop type T_Tags_PicturesID;
drop type T_RepostsID;
drop type T_ChildPoolsID;
use master;
go*/
use master;
drop database Gallery;
go
